### ISSUE TITLE
Outdated Depenedencies

### ISSUE THREAD

**Issue by nnance** [sabarasaba/modern-backbone-starterkit#10]
I am a long time Backbone developer and evangelist.  I really like the tools you have selected in this project and I have based a couple of my projects on it.  Would you be interested in help with maintaining the project?  specifically a PR for updating the dependencies?

**Comment by sabarasaba** [comment]
Hey man, yeah of course! I've been wanting to close that one for a while; Ill make you a contributor right away :)

**Comment by gitlovenotwar** [comment]
Hi, it's been a year already since this was closed. I've been using this starter kit since I've started using backbone, but the dependencies kind of outdated. Is there an update on this or fork somewhere? :)

**Comment by sabarasaba** [comment]
@gitlovenotwar True, I havent been giving this repo the love it deserves. I'll spend some time this weekend and make sure it's amazing again :)

**Comment by sabarasaba** [comment]
@gitlovenotwar @nnance Done, hope you enjoy it!
