### ISSUE TITLE
HMR is not updating DOM

### ISSUE THREAD

**Issue by marekkaczkowski** [sabarasaba/modern-backbone-starterkit#16]
When changes are saved in for eg.  `HomePage.js` console output looks ok:
```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ./src/app/components/home-page/HomePage.js
[HMR] App is up to date.
```
in HMR response `0.*************************.hot-update.js` I can see changes saved in `HomePage.js`
but DOM tree is not updating and have to manually hit `CMD+R`. Am I missing something in configuration?

**Comment by sabarasaba** [comment]
@marekkaczkowski that last commit on master should fix it, lemme know how it works out :)
