### ISSUE TITLE
gulp-webpack deprecated

### ISSUE THREAD

**Issue by kasteph** [sabarasaba/modern-backbone-starterkit#3]
The author of `gulp-webpack` has stopped support of this particular package (since 4 months I believe). His new gulp webpack plugin is at `https://www.npmjs.com/package/webpack-stream`.

**Comment by sabarasaba** [comment]
@stephsamson Thanks for letting me know, should be fixed with https://github.com/sabarasaba/modern-backbone-starterkit/commit/b0a52f6e8cacffade58252920787f5f833e0114c
