### ISSUE TITLE
gulp-uglifyjs is blacklisted

### ISSUE THREAD

**Issue by paulfalgout** [sabarasaba/modern-backbone-starterkit#6]
Any reason to not use `gulp-uglify` and then people can add `gulp-concat` if necessary?

**Comment by sabarasaba** [comment]
Hey, sorry it took a while to get back to you. Not really, I wasn't aware that module got blacklisted- I'll fix it during this week. Thanks !

**Comment by ebramanti** [comment]
@sabarasaba Any update on this?

**Comment by sabarasaba** [comment]
Maybe @nnance can give us a hand ?
