### ISSUE TITLE
Updating `template.hbs` doesn't appear to update view since `router.js` overrides template

### ISSUE THREAD

**Issue by crcatala** [sabarasaba/modern-backbone-starterkit#7]
Since `router.js` overrides the template, if you make a change to `template.hbs` a newb might wonder if something is broken if they don't pick up on what's happening here. Ex:

https://github.com/sabarasaba/modern-backbone-starterkit/blob/master/src/app/router.js#L20

Also the inconsistency in using the `<%= name %>` on an inline template vs using handlebars in .hbs templates.

**Comment by sabarasaba** [comment]
Good catch man, sorry it took a while to fix!

**Comment by crcatala** [comment]
Thanks for the fix @sabarasaba :palm_tree:
